### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by bcardarella** [lomboboo/webpack2-typescript-seed#1]
I just tried `npm install` with 10.6.2 and it bombs out. Which version of node are you using to build?

**Comment by lomboboo** [comment]
I'm using v8.9.4, but I've just tried with v10.6.0 and it seems to install just fine. Can you attach some logs or errors you get, as well as output `node -v`?

**Comment by lomboboo** [comment]
I'm closing the issue due to inactivity. Feel free to reopen if you'll get the same problems if the future.
